port: 8080

mongodb:
  uri: "mongodb://root:wifi-2026!@mongodb:27017/wifi_portal?authSource=admin"
  db_name: "wifi_portal"

redis:
  addr: "redis:6379"
  password: "redis-2026!"
  db: 0

sms:
  price_per_sms: 6

security:
  sms_cooldown: 60
  ip_cooldown: 60
  max_sends_per_day: 5
  code_expire_minutes: 5
  max_attempts: 3